### ISSUE TITLE
No precompiled templates

### ISSUE THREAD

**Issue by dhaubert** [simonprickett/bartcordova#1]
Hey there, 
I have seen that in the last changes you updated all to precompiled templates. I'm trying to apply handlebars to a project but i'm newbie at this library yet. If you want to contribute with me and anybody else that want to learn about it, could you submit www/js/precompiled-templates.js?

Best regards

**Comment by simonprickett** [comment]
Hi there - sorry for the super slow response to this, it's been like 6 months... the templates are compiled whenever the Cordova CLI rebuilds the application, the command that compiles them is in this script: https://github.com/simonprickett/bartcordova/blob/master/scripts/before_build.sh

**Comment by dhaubert** [comment]
Thanks
